version: 2

updates:
  - package-ecosystem: "terraform"
    directory:
      - modules/sso
      - modules/sso/modules/account-assignments
      - modules/sso/modules/permission-sets
    schedule:
      interval: "daily"
